name = "Create: Murder and Machines"
author = "QPCrummer"
version = "1.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bccf11fb01697c9db60123853eef9dc023d1550614dfa85a8ed98c05883b2152"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
