name = "Create: Murder and Machines"
author = "QPCrummer"
version = "1.0.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6d1a48e9d9fdce28da0f4c4ea1f8100edd8b15ff5398812998c3a14d85b9afe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
